name: GitHub Classroom Workflow

on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/*'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: gtest
    timeout-minutes: 5
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Check
        run: |
             !(grep -qwRE --include=*.{cpp,h,hpp} '<vector>|<list>|<algorithm>|<stack>|<queue>|<deque>|<set>|<map>|<bits' ./* ) &&  (echo \"Check - OK\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
      - name: Check code style
        run: |
             clang-format --version
             find "." \( -name '*.cpp' -o -name '*.h*' \) -print0 | xargs -0 clang-format --dry-run --Werror --verbose
      - name: Code linting
        uses: amcp-pit/cpp-linter@v1
        with:
          extra-args-before: '-xc++'
          extra-args: '-std=c++20'
          after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - name: Build
        run: |
             cmake .
             cmake --build .
      - name: Autograding
        uses: amcp-pit/autograding@v1
      - name: Memory leaks
        run: |
             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./biginttest
             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./decode tests/key1.txt tests/msg10.txt
      - name: Benchmark
        run: |
             timeout 60 ./benchmark
             timeout 60 ./benchmark-fast
      - name: Checkout
        uses: actions/checkout@v4
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner  }}
      - name: Clean
        run: |
             rm -rf ./* || true
             rm -rf ./.??* || true
